// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'
// import { Toaster } from 'sonner'
// import { SessionProvider } from 'next-auth/react'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang='en' className='scroll-smooth'>
    
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900  bg-background`}
//         >
//           <main className='min-h-screen '>
//             <SessionProvider> {children} </SessionProvider>
//             </main>
//           <Toaster position='top-center' richColors />
//         </body>
       
//     </html>
//   )
// }
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { SessionProvider } from 'next-auth/react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  metadataBase: new URL("https://yourdomain.com"), // ✅ replace with your production domain
  title: 'My E-commerce',
  description: 'The best place to shop online',
  openGraph: {
    title: 'My E-commerce',
    description: 'The best place to shop online',
    url: 'https://yourdomain.com',
    siteName: 'My E-commerce',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'My E-commerce Preview',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'My E-commerce',
    description: 'The best place to shop online',
    images: ['/og-image.png'],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900 bg-background`}
      >
        <main className='min-h-screen'>
          <SessionProvider>{children}</SessionProvider>
        </main>
        <Toaster position='top-center' richColors />
      </body>
    </html>
  )
}
