import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { Toaster } from 'sonner'
import NavMenu from '@/components/shared/header'
import Footer from '@/components/shared/Footer'
import { SessionProvider } from 'next-auth/react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900`}
      >
        <NavMenu />
        <SessionProvider>
          <main className='min-h-screen mx-1.5'>{children}</main>
        </SessionProvider>
        <Toaster position='top-center' richColors />
        <Footer />
      </body>
    </html>
  )
}
